Product-0.0.1-SNAPSHOT
# Start with a base image containing Java runtime
FROM openjdk:17-jdk-slim as build

# Information around who maintains the image
MAINTAINER jsc.com

# Add the application's jar to the container
COPY target/ Product-0.0.1-SNAPSHOT .jar Product-0.0.1-SNAPSHOT.jar

# Execute the application
ENTRYPOINT ["java", "-jar", "/Product-0.0.1-SNAPSHOT.jar"]